name: Demo Secret Env Var

on:
  workflow_dispatch:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print safe message
        run: |
          echo "🚀 The secret is stored securely."
          echo "We won’t print it to keep it safe."
        env:
          SECRET_KEY: ${{ secrets.password }}
